### ISSUE TITLE
Disabled in this strategy. Migrate your assets using the website.

### ISSUE THREAD

**Issue by olegabr** [harvestfi/dashboard#13]
After connecting my MM wallet I'm getting this error in browser console and see no assets result on a page.

![image](https://user-images.githubusercontent.com/2850808/97535581-702f7000-19ee-11eb-9996-ba0e25b586f7.png)

Full error text:
```
Uncaught (in promise) Error: call revert exception (method="getPricePerFullShare()", errorSignature="Error(string)", errorArgs=["Disabled in this strategy. Migrate your assets using the website."], reason="Disabled in this strategy. Migrate your assets using the website.", code=CALL_EXCEPTION, version=abi/5.0.4)
```

Note, I have not done any transaction, just pressed the `Connect Wallet` button.

I'm using Chromium browser on Ububntu GNU/Linux system.

**Comment by brandoncurtis** [comment]
This happened because the active pool list had not been updated to account for vaults—the v0 non-timelocked vaults for stablecoins, btc synths, and Uniswap LP positions—that had been deprecated and disabled.  Fixed now!

If it appears again, dear devs: ensure that the newest active vault information is available in deploys.js.

**Comment by olegabr** [comment]
The https://harvestfi.github.io/dashboard/ page is still broken and https://harvest.finance/ page has a direct link on it from the main menu.

**Comment by brandoncurtis** [comment]
@olegabr can you be more specific about how it's broken? Are you holding old vault v0 assets that you never migrated?  v0 assets can no longer be minted, so this is hard to test now and no one else has reported a problem.
